# Jekyll configuration

whitelist:
  - jekyll-redirect-from
  - jekyll-github-metadata
  - jekyll-extlinks

plugins:
  - jekyll-redirect-from
  - jekyll-github-metadata
  - jekyll-extlinks

exclude:
  - .babelrc
  - .cache
  - CNAME
  - CONTRIBUTING.md
  - cssnano.config.js
  - docker_compose.yml
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - Makefile
  - node_modules
  - package.json
  - package-lock.json
  - postcss.config.js
  - README.md
  - vendor
  - webpack.config.js
  - yarn-error.log
  - yarn.lock

extlinks:
  attributes: {rel: nofollow, target: _blank}
  rel_exclude: ['11meigui.com']


# Markdown

highlighter: false
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true
  syntax_highlighter_opts:
    disable: true

# Defaults

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: "default"
      og_type: article
      type: article
      category: "Others"
      excerpt_separator: "<!--更多-->"
      prism_languages: []

# Site info

url: https://11meigui.com/dev
title: 11meigui.com 全栈开发速查表
# GitHub metadata
# https://help.github.com/articles/repository-metadata-on-github-pages/

repository: jackzing/cheatsheets
